service: discord-saturn

provider:
  name: aws
  runtime: python3.8
  environment:
    STAGE: ${sls:stage}

  tags:
    application: saturn

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters

functions:
  entry:
    handler: discord.main
    events:
      - httpApi:
          method: POST
          path: /v1/signup
    layers:
      - arn:aws:lambda:us-east-1:#{AWS::AccountId}:layer:salt:1
